kakao:
  rest-api-key: 5873946df1528ff9ccf0570a3d7a8cf6
  url:
    blog-search: https://dapi.kakao.com/v2/search/blog

naver:
  client-id: 3Sc7wvxCuwvgivmJ9jRf
  client-secret: xsOkNF0gqE
  url:
    blog-search: https://openapi.naver.com/v1/search/blog.json